[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "PEAKModding"
name = "PEAKLib_Core"
description = "Core module of the PEAKLib community API."
websiteUrl = "https://github.com/PEAKModding/PEAKLib/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
PEAKModding-SoftDependencyFix = "1.0.0"
MonoDetour-MonoDetour_BepInEx_5 = "0.6.7"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../../artifacts/thunderstore/"

[[build.copy]]
source = "../../../artifacts/bin/PEAKLib.Core/release/com.github.PEAKModding.PEAKLib.Core.dll"
target = "plugins/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", "libraries", "client", ]
