name: Publish

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+-dev"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Restore
        run: |
          dotnet restore --locked-mode
          dotnet tool restore

      - name: Pack and Publish Thunderstore
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
        run: dotnet pack -c Release --no-restore -target:PackTS -property:PublishTS=true -v d

      - name: Publish NuGet
        run: dotnet nuget push ./artifacts/package/release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
